### ISSUE TITLE
Filters API :)

### ISSUE THREAD

**Issue by GoodBoyDigital** [pixijs/pixi-sound#1]
I had a dream where to apply filters to sound it was a simple as this:

```
var mySound = Sound.from('happy-days.mp3')
var filter = new PitchShiftFilter();

mySound.filters = [filter];
```

**Comment by bigtimebuddy** [comment]
Done! This is in the dev branch. I added filters:
* ReverbFilter
* EqualizerFilter
* DistortionFilter 
* StereoFilter

**Comment by GoodBoyDigital** [comment]
amazing man! you are flying :)
