### ISSUE TITLE
Probably a typo

### ISSUE THREAD

**Issue by Corginyan** [pixijs/pixi-sound#101]
https://github.com/pixijs/pixi-sound/blob/9f18e27997e5153fe8ef04a36e4489e986b180d9/pixi-sound.d.ts#L52

https://github.com/pixijs/pixi-sound/blob/9f18e27997e5153fe8ef04a36e4489e986b180d9/src/Sound.ts#L12

**Comment by bigtimebuddy** [comment]
Yes typo. Good one
