### ISSUE TITLE
Sound loading broken in iOS 10 Safari

### ISSUE THREAD

**Issue by ericente** [pixijs/pixi-sound#104]
I get this error `IndexSizeError (DOM Exception 1): The index is not in the allowed range.` from `createScriptProcessor` on iOS 10 Safari, starting with pixi-sound version 2.1.1. This appears to be introduced by this PR: https://github.com/pixijs/pixi-sound/pull/88

**Comment by ericente** [comment]
from MDN: `Important: Webkit currently (version 31) requires that a valid bufferSize be passed when calling this method.`

**Comment by bigtimebuddy** [comment]
I think I need to drop the ScriptProcessor node all together. It performs poorly, and I'm only really using it for update events/timing. Switching to Pixi's ticker will probably fix this.

Temporary fix might be to add back the ability to set the buffer size (default to 0 except when iOS then set another default).
