### ISSUE TITLE
fs dependency no longer available on npm

### ISSUE THREAD

**Issue by dschreij** [pixijs/pixi-sound#11]
I was importing pixi-sound and got the error message:

~~~
ERROR in ./~/pixi-sound/lib/Sound.js
Module not found: Error: Can't resolve 'fs' in '/Users/daniel/Sites/osweb/node_modules/pixi-sound/lib'
 @ ./~/pixi-sound/lib/Sound.js 333:17-30
 @ ./~/pixi-sound/lib/deprecations.js
 @ ./~/pixi-sound/lib/index.js
~~~

Apparently, the Sound module tries to use the fs (filesystem?) module to read a file from disk, but the fs module is no longer available on npm, according to the readme file of fs:

~~~
# Security holding package

This package name is not currently in use, but was formerly occupied
by another package. To avoid malicious use, npm is hanging on to the
package name, but loosely, and we'll probably give it to you if you
want it.

You may adopt this package by contacting support@npmjs.com and
requesting the name.
~~~

Additionally, the fs module is not listed as a dependency on pixi-sound's npm page.

What's the best approach here? Replace fs with a module with similar functionality?

**Comment by dschreij** [comment]
I just realized that fs should be part of the node.js default modules! Strange that it can't find the module on my system then...

**Comment by dschreij** [comment]
This seems to be an issue with webpack, rather than with your library: https://github.com/josephsavona/valuable/issues/9

Sorry for reporting this here. Closing the issue!

**Comment by bigtimebuddy** [comment]
Thanks for digging into this @dschreij. Useful information for people using Webpack.
