### ISSUE TITLE
sound does not exist when using Typescript and Webpack

### ISSUE THREAD

**Issue by mobileben** [pixijs/pixi-sound#119]
I started to add audio as the last part of building my current game. This is my first HTML5 game, so I have been going through a learning curve. 

I've looked at this: https://github.com/bigtimebuddy/pixi-sound-webpack-example

As well as some other comments. I've loaded my sound assets during my loading phase (along with the textures).

In the typescript file I want to play, I imported with the following (which is similar to what is used in  the pixi-sound-webpack-example)

```
import * as PIXI from 'pixi.js'
import sound from 'pixi-sound'
```

Then to play, I try

```
sound.play('test');
```

I've also tried it with adding the argument `{loop: false}`. 

What I find is that `sound` is undefined.

I'm using PIXIJS 5.2.0 and 

    "pixi-sound": "^3.0.4"

The only main diff I have in my package.json is that it's under `dependencies` not `devDependencies`.

I also looked at the app.js generated in the dist directory. And it does appear to contain `pix-sound`.

I saw this issue. https://github.com/pixijs/pixi.js/issues/5948. Not sure if there is any relationship. But just in case, these are the loaders in my package-lock.json file.

        "@pixi/loaders": {
            "version": "5.2.0",
            "resolved": "https://registry.npmjs.org/@pixi/loaders/-/loaders-5.2.0.tgz",
            "integrity": "sha512-lKd5RYGQ86NoQNFcu/IYLEkC/oa6XypDKewG9LDd7n9XKKeed0NRipg7HhcYVsliayYkszoQ/JdzidV/yxnHYw==",
            "requires": {
                "@pixi/core": "^5.2.0",
                "@pixi/utils": "^5.2.0",
                "resource-loader": "^3.0.1"
            }
        }

**Comment by bigtimebuddy** [comment]
Could you please provide a repo that reproduces the problem so I can help troubleshoot? Sometimes these webpack issues are subtle.

**Comment by bigtimebuddy** [comment]
@mobileben could you please provide a reproducible example of this issue you’re seeing? It’s hard to tell based on your description what is happening

**Comment by mobileben** [comment]
@bigtimebuddy I am working on this. I built a sample case, but it works. My project is too large and I don't want to distribute that code, so trying to isolate it. I was using an `npm link` to an experimental version of pixi.js. Basically my version with a mod for textures, which "should" have no impact.

If I disabled the link, uninstalled, then installed pixi.js (`npm install --save pixi.js`), then it mostly worked. I say mostly because it would still occasionally fail.

Some things I've noticed:

In both my simple case and when I installed pixi.js, I would get this warning in the console (I'm on Chrome).

>The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page.

Also, when trying to run sound, it actually exists as an object if I do `console.log("Sound is " + sound);`. In my output I see

Sound is [object Object]
Uncaught TypeError: Cannot read property 'play' of undefined
  t.play	
  (anonymous function)	
  emit	
  handleScoreEvent	
  update	
  update	
  (anonymous function)	
  emit	

This is slightly confusing, since `sound` is an object, but yet when I try and play, it indicates `sound` is undefined. The specific lines are:

```
console.log("Sound is " + sound);
sound.context.paused= false;
sound.play('test');
```

This along with noticing that the resource for the asset doesn't have a `sound` property makes me wonder if there is an issue with how `pixi-sound` is started. Like there perhaps needs to be some explicit boot strap or there is some form of order dependency.

**Comment by mobileben** [comment]
Also not sure if this helps, but I dumped out the keys for the sound object:

```
            Object.keys(sound).forEach((key) => {
                console.log("Sound key " + key);
            });
```

This is the output

> Sound is [object Object]
> Sound key _webAudioContext
> Sound key _htmlAudioContext
> Sound key _sounds
> Sound key _useLegacy
> Sound key _context

**Comment by bigtimebuddy** [comment]
There’s a lot of things going on here. One obvious thing is that you’re going to have issues linking pixi.js into your project and building with Webpack. Because of the structure of the pixi.js monorepo, it’s not easy to link everything to import cleanly. It’s a known issue, and most people hack around it. If that dependency tree doesn’t come in correctly all bets are off.

The second issue around gesture required is a browser issue. Your first sound needs to be initiated on a touch or mouse event to initial the AudioContext.

For the other issues, I’d need to see a reproducible example to know but maybe a symptom of the linking?

**Comment by mobileben** [comment]
Understood you would need a reproducible example. However I agree with you that It think this is a manifestation of the linking. I'm going to try some experiments later, but I think part of the issue with the linking is that pixi uses an @pixi folder which ends up on node_modules, but the bundle built has that node_modules there. So I wonder if this becomes part of the issue. I've run a diff and that is the major variance between the two.

A bit of a bummer since it is convenient at times to run ones own version of pixi and debug the code in a more streamlined fashion. 

I'll keep this open a little bit longer whilst I investigate, in case I can make a solid reproducible example. Else, I'll close it.

Thanks for your reply.

**Comment by bigtimebuddy** [comment]
Consider making a new issue on pixi.js to add support for npm/yarn linking and bundling (Webpack). I’m sure there’s a solution, just not sure what it is yet but this has come up a few times and we should probably address.

**Comment by mobileben** [comment]
I opened an issue as you suggested.  I've tried to mess around with some variants and I think the problem relates to pixi's scoped packages. Guessing ... but it would seem that one would need to also link each of the scoped packages as well, which is a bit of a PITA to do. In particular, because if one is building from the pixi.js source (via `npm run build`), the generated scoped packages are symbolic links but also contain node_modules, and are also flattened out (the filters). I went through some of the config files, like the lerna files, and it seems that when things are submitted, they are probably bundled a certain way. It would be nice if there was a way to layout out a "proper" node_modules directory structure for pixi.js to help facilitate npm linking.

BTW, my workflow was (in my fork of pixi.js)

- Make my changes
- Build using `npm run build`.

My bundles/pixi.js directory was linked. I actually manually created the symbolic links to /usr/local/libs/node_modules and to my project as well as used `npm link` to create them.

I found I could use the pixi.es.js file (not sure why that file) to set breakpoints and debug my pixi.js code.

This to me is a "reasonable workflow" (if it worked) because it allows for rapid development.

Just out of curiosity, how do you build and test your stuff? I'm guessing that the core pixi team members all use a similar successful methods that others are not using?
