### ISSUE TITLE
Doesn't work on ios safari

### ISSUE THREAD

**Issue by hendrysadrak** [pixijs/pixi-sound#12]
In devtools: `[Error] SyntaxError: Cannot declare a parameter named 'panning' as it shadows the name of a strict mode function.`

**Comment by bigtimebuddy** [comment]
Stack trace? What browser?

**Comment by hendrysadrak** [comment]
ios safari, no stacktrace, but can give line
![image](https://cloud.githubusercontent.com/assets/4000963/24702746/e56a1b20-1a08-11e7-9a06-7e8eb0ebaf27.png)

**Comment by hendrysadrak** [comment]
So issue comes  from https://github.com/pixijs/pixi-sound/blob/master/src/deprecations.ts#L26

**Comment by bigtimebuddy** [comment]
I think this is because the parameter is the same name as the function. Could you try something and change the parameter to "panningValue" from "panning" and see if that fixes the error?

**Comment by hendrysadrak** [comment]
will try in sec

**Comment by hendrysadrak** [comment]
yep, this fixes it

**Comment by bigtimebuddy** [comment]
Thanks for your help on this.

**Comment by hendrysadrak** [comment]
No probs! And #6 Would be awesome 😁
