### ISSUE TITLE
PIXI.sound.pauseAll()

### ISSUE THREAD

**Issue by Article19** [pixijs/pixi-sound#130]
If I do this:

PIXI.sound.pauseAll()
PIXI.sound.play(somesound)

somesound won’t play. Even this won’t work:

PIXI.sound.pauseAll()
PIXI.sound.play(somesound)
PIXI.sound.resume(somesound)

I suspect pauseAll may be doing its thing asynchronously and any attempt to play a sound right after issuing the call will fail. Any insights? Perhaps I'm not understanding how this is supposed to be working?

**Comment by andrewstart** [comment]
`pauseAll()` pauses the entire (WebAudio or HTMLAudio) sound context, so no sound will play. The method description could stand to be a little more accurate about that.

**Comment by Article19** [comment]
Ok - thanks!

**Comment by creyD** [comment]
@Article19 Could this be closed then?

**Comment by Article19** [comment]
Yes, I suppose it could (though, imo, there is lingering confusion about how this is to be used).
