### ISSUE TITLE
Provide versioned url for download

### ISSUE THREAD

**Issue by sniperliu** [pixijs/pixi-sound#16]
I am trying to package pixi-sound for cljsjs (clojurescript). The tool need versioned url for package and maintenance. Is that possible to provide a versioned url for download like https://pixijs.github.io/pixi-sound/dist/pixi-sound-1.4.1.js & pixi-sound-1.4.1-min.js? Or they are somewhere I did not find?

Thanks in advance.

**Comment by bigtimebuddy** [comment]
You can use these:
https://github.com/pixijs/pixi-sound/releases/download/v1.4.1/pixi-sound.min.js
https://github.com/pixijs/pixi-sound/releases/download/v1.4.1/pixi-sound.js
