### ISSUE TITLE
PIXI's Loader is not loading sounds as ArrayBuffer, unable to decode

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-sound#18]
As reported by @funkypaul on pixi.js Slack...

This works fine.

```js
let soundsMap = {
    "game_start": "assets/sounds/game_start.ogg",
    "spin_ready": "assets/sounds/spin_ready.ogg",
    "spin_loop": "assets/sounds/spin_loop.ogg",
    "spin_stop": "assets/sounds/spin_stop.ogg",
    "win_loop": "assets/sounds/win_loop.ogg",
    "game_end": "assets/sounds/game_end.ogg",
    "spin_start": "assets/sounds/spin_start.ogg",
    "spin_tick": "assets/sounds/spin_tick.ogg"
};
sound.add(soundsMap, {
    preload: true
});
```

This throws the error below:

```js
let loader = new PIXI.loaders.Loader();
loader
    .add("game_start", "assets/sounds/game_start.ogg")
    .add("spin_ready", "assets/sounds/spin_ready.ogg")
    .add("spin_loop", "assets/sounds/spin_loop.ogg")
    .add("spin_stop", "assets/sounds/spin_stop.ogg")
    .add("win_loop", "assets/sounds/win_loop.ogg")
    .add("game_end", "assets/sounds/game_end.ogg")
    .add("spin_start", "assets/sounds/spin_start.ogg")
    .add("spin_tick", "assets/sounds/spin_tick.ogg")
    .add("font_dark", "assets/fonts/font_dark.fnt")
    .add("font_light", "assets/fonts/font_light.fnt")
    .load(function (loader, resources) {
        this.loadAnimateScene();
    }.bind(this));
```

```
Uncaught (in promise) TypeError: Failed to execute 'decodeAudioData' on 'BaseAudioContext': parameter 1 is not of type 'ArrayBuffer'.
    at SoundContext.decode (SoundContext.js:156)
    at Sound._decode (Sound.js:355)
    at Sound._beginPreload (Sound.js:295)
    at new Sound (Sound.js:54)
    at SoundLibrary.add (SoundLibrary.js:65)
    at Loader.middleware (LoaderMiddleware.js:7)
    at Loader.js:590
    at next (async.js:32)
    at Loader.bitmapFontParser (bitmapFontParser.js:10)
    at Loader.js:590
```

## Environment
* Windows 8
* Chrome 57 (64-bit)
* pixi-sound@1.4.1
* pixi.js@4.4.3, pixi.sj@4.5.1
* problem with ogg and mp3

**Comment by bigtimebuddy** [comment]
The problem is **pixi-animate** setting audio files to load as `<audio>` elements. See [here](https://github.com/jiborobot/pixi-animate/blob/master/src/animate/load.js#L3-L5).  This should be removed since that's the [default](https://github.com/englercj/resource-loader/blob/master/src/Resource.js#L1002-L1004) for audio elements using resource-loader anyways.

This is something added here https://github.com/jiborobot/pixi-animate/pull/16. I don't think there are consequences for removing it. @ianmcgregor thoughts?

**Comment by funkypaul** [comment]
The workaround is to make sure that the 

`import "pixi-animate";`

is called before 

`import "pixi-sound";`

**Comment by ianmcgregor** [comment]
Yeah at the time resource-loader didn't have audio extensions set up by default but that has long since been resolved so we can safely remove that. I can submit a PR, unless you're already on it?

**Comment by bigtimebuddy** [comment]
Could you make the PR? Thanks
