### ISSUE TITLE
Add support for different audio format

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-sound#22]
Suggest using a glob-like API which allows you to set type for loading different audio files.

```js
PIXI.sound.add('music', 'sounds/music.{mp3,ogg}');
```

In this case, mp3 would be loaded highest-priority with fallback to ogg.

**Comment by englercj** [comment]
most systems use an array of urls and chose the one the browser supports at runtime. For example, I use different paths for different formats of sounds.

**Comment by englercj** [comment]
The loader does this by adding each url as a "source" and letting the browser decide which to load.

**Comment by bigtimebuddy** [comment]
Yup, that's my assumption too. In my example above, if `sounds/music.mp3` cannot be played, will use `sounds/music.ogg`. I wanted something that's not super verbose. Currently pixi sound only supports a single file.
