### ISSUE TITLE
Error with library fs

### ISSUE THREAD

**Issue by davidgit75** [pixijs/pixi-sound#28]
Hello, I'm getting this error and I can't start my application,

`
ERROR in ./node_modules/pixi-sound/lib/Sound.js
    Module not found: Error: Can't resolve 'fs' in '/Users/davidh/Documents/Jobs/XXXX/node_modules/pixi-sound/lib'
    resolve 'fs' in '/Users/davidh/Documents/Jobs/XXXX/node_modules/pixi-sound/lib'
      Parsed request is a module
      using description file: /Users/davidh/Documents/Jobs/XXXX/node_modules/pixi-sound/package.json (relative path: ./lib)
        Field 'browser' doesn't contain a valid alias configuration
`

I tried installing fs and doesn't work, I added this configuration to the webpack and continue without working

`
target: 'node'
node: { fs: 'empty' }
`

**Comment by bigtimebuddy** [comment]
Thanks for the tip. This has been resolved in v2.0.0-alpha (replaced Browserify with Rollup) and does a better job using `fs`.

**Comment by davidgit75** [comment]
I installed the v2.0.0-alpha and continue with the same error. Is necessary an aditional configuration? Thanks

`
ERROR in ./node_modules/pixi-sound/dist/pixi-sound.es.min.js
    Module not found: Error: Can't resolve 'fs' in '/Users/davidh/Documents/Jobs/Victory/6051-T4L/node_modules/pixi-sound/dist'
    resolve 'fs' in '/Users/davidh/Documents/Jobs/Victory/6051-T4L/node_modules/pixi-sound/dist'
      Parsed request is a module
      using description file: /Users/davidh/Documents/Jobs/Victory/6051-T4L/node_modules/pixi-sound/package.json (relative path: ./dist)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: /Users/davidh/Documents/Jobs/Victory/6051-T4L/node_modules/pixi-sound/package.json (relative path: ./dist)
`

**Comment by bigtimebuddy** [comment]
You're using Webpack?

**Comment by bigtimebuddy** [comment]
I was able to suppress this issue by changing my Webpack configuration. Here's an example:

```js
module.exports = {
    entry: './src/index.js',
    output: {
        path: __dirname + '/dist',
        filename: 'bundle.js'
    },
    node: {
        fs: "empty"
    }
};
```

The important bit is 
```
node: {
    fs: "empty"
}
```

Reference https://github.com/josephsavona/valuable/issues/9#issuecomment-313720759
