### ISSUE TITLE
Publish pre-releases on npm

### ISSUE THREAD

**Issue by raffomania** [pixijs/pixi-sound#32]
I would like to use the 2.0.0 alpha in my project, but don't want to build the files myself every time. Could you publish the pre-releases to npm? According to [this post](https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420), this is preferrably done using a custom tag:
```
npm publish --tag alpha
```
otherwise, npm seems to install pre-releases by default when installing without a version number (e.g. `npm install pixi-sound`).

**Comment by bigtimebuddy** [comment]
They are published under the "canary" tag.

npm install pixi-sound@canary
