### ISSUE TITLE
RFC: Option for sound context [auto|re]initialization

### ISSUE THREAD

**Issue by cursedcoder** [pixijs/pixi-sound#33]
### Status

At the moment sound context is always automatically created within SoundLibrary

### Why it is not good

When context is created it is bound with sound hardware, so it always consumes resources.

There may be situations when hardware is blocked at the moment SoundLibrary being created.

My personal real cases:
* On iOS cordova background plugin will rebind audio sources when used, this will always halt existing audio contexts.
* Opening page with just pixi-sound included produces "soft noise" – when empty sound is streamed to audio output.

### Proposal

1. Add option `autoInitialize` – self-explanatory.
2. Add interface `SoundLibrary.rebuildContext()` – or similar, this will provide users ability to recover from any hardware interruptions.

**Comment by bigtimebuddy** [comment]
How about adding methods `PIXI.sound.destroy()` & `PIXI.sound.init()` so that the library can be re-initialized (i.e., recreate the sound context)?

**Comment by cursedcoder** [comment]
@bigtimebuddy that's good!
