### ISSUE TITLE
Unable to use this lib in browser

### ISSUE THREAD

**Issue by PainKKKiller** [pixijs/pixi-sound#39]
Hello! Project seems excellent, but when I tried to use it in my code, I've got error

`./~/pixi-sound/lib/Sound.js
Module not found: Error: Can't resolve 'fs' in '/home/user/Desktop/projects/balls/monster_cash/node_modules/pixi-sound/lib'`

and as I see in Sound.js on 334 line there is var fs = require("fs"); And as far as I know it is node.js native module. How can I use it in browser? Or may be I have wrong import (I use ES6 modules with webpack). Didn't find any example how to import module in your docs, but it isn't working without it 

`import Sound from 'pixi-sound';`

Does it right?

**Comment by PainKKKiller** [comment]
If I don't do import PIXI.sound is undefined

**Comment by PainKKKiller** [comment]
Sorry, it was some strange issue, now it's working

**Comment by PainKKKiller** [comment]
All works but I see this error in console

**Comment by bigtimebuddy** [comment]
Please upgrade to v2.0.0-alpha.6 instead of the latest release. This should be fixed.

**Comment by bigtimebuddy** [comment]
Related https://github.com/pixijs/pixi-sound/issues/28

**Comment by PainKKKiller** [comment]
Thanks for quick reply, it fixed
