### ISSUE TITLE
[feature] Implement fadeIn and faceOut methods

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-sound#4]
Add methods for fading in and out of the volume levels when playing or stopping audio. For instance:

```js
const sound = PIXI.sound.Sound.from('foo.mp3');
const instance = sound.fadeIn(500); // same as play()
instance.fadeOut(200); // fade out a single instance
sound.fadeOut(200); // fade out all instances
```

And global library commands:

```js
PIXI.sound.add('foo', 'foo.mp3');
const instance = PIXI.sound.fadeIn('foo', 500);
instance.fadeOut(200); 
PIXI.sound.fadeOut('foo', 200); // fade out all instances
PIXI.sound.fadeOut(); // fade out all sounds, all instances
```

**Comment by alvinsight** [comment]
Hi Matt,
Sorry just catching up on Pixi Sound, this is a great idea!
One thing we struggled with when using Howler was the lack of a reliable `volume` getter, I had to patch around it quite a lot.
With this, it's easy to then use any tweening engine, even something tiny like https://www.npmjs.com/package/tweenr
My point is I don't think it's worth spending a lot of time making `fadeIn` super efficient, but have good getter/setters :)
Obviously just my 2 cents

**Comment by bigtimebuddy** [comment]
Hi @alvinsight, thanks for the feedback.

I see the point, but I still might add these convenience methods anyways. I think fading in and out is pretty basic functionality and in this case it's just a linear tween. The good thing is that the current webaudio playback has a pretty good progress events, so there wouldn't need to rely on an internal tweening structure or another ticker/requestAnimationFrame. 

If it's low-cost, low-effort, I'll implement. Otherwise, I'll take your advice and allow devs to do their own tweening.

**Comment by alvinsight** [comment]
Hi Matt,
Great, that's exactly my point, I agree that it's a basic feature that one can expect at a basic level.
I just wanted to make sure it's low-effort and we don't reinvent the wheel with another Ticker, as you said :)

**Comment by Lusito** [comment]
I don't think this is actually solved... there is no fadeOut method in SoundInstance.
I want to be able to stop a looping sound by fading it out rather than stopping it instantly. The original request seems to propose that, but the current implementation does not support it.

**Comment by flahhi** [comment]
Faced with the same problem. I can't find fadeIn / fadeOut
@Lusito did you find the solution

**Comment by bigtimebuddy** [comment]
I had implemented this for v1 but removed it it for v2 because I wanted to give more flexibility. So instead I implemented per soundinstance, per Sound and per context volume setting, as well as html5 audio fallback which complicated the fades. In the end, I didn’t want to include any tweening and felt like other people might have opinionated implementations of this functionality. I’d recommend greensock or some other tween library to manage fades.

**Comment by JoeMGomes** [comment]
Is there any documentation/reference that I could look at to implement this myself with pixi-sound.js v4? I just need a simple linear fade in/out

**Comment by bigtimebuddy** [comment]
Here's a working example using GSAP:
https://codesandbox.io/s/pixijs-examples-sound-fade-out-qcos8n?file=/src/index.ts

The part you'll really care about is this:

```ts
const instance = buzzer.play();
gsap.to(instance, { volume: 0, duration: 1 });
```

There are other libraries out there for tweening that would basically do the same thing.
