### ISSUE TITLE
Now, need to use setTargetAtTime/setValueAtTime

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-sound#40]
see https://www.chromestatus.com/features/5287995770929152

We can't set 'value' directly any more.
e.g

current
```
gainNode.gain.value = 0.6
```

change to
```
gainNode.gain.setValueAtTime(0.6, context.currentTime);
```

But some old browsers (e.g. some android webviews) don't support setTargetAtTime/setValueAtTime.

So , we need to check it .

In my own sound lib , I use this : 
```
    Sound.setAudioParamValue = function(nodeParam, value, context) {
        if (nodeParam.setValueAtTime) {
            nodeParam.setValueAtTime(value, context.currentTime);
        } else {
            nodeParam.value = value;
        }
    };
```

**Comment by bigtimebuddy** [comment]
Thanks for pointing this out, submitted #41 if you could take a look.

**Comment by finscn** [comment]
I've too a look. I think it's no problem. 
 But I'm not test , just review by my eyes.
Because I've never use pixi-sound, I don't have enough time to learn how to use it.
