### ISSUE TITLE
Problems with sound in latest Chrome on Android in iframe

### ISSUE THREAD

**Issue by PainKKKiller** [pixijs/pixi-sound#49]
Sorry for vague description of the problem, but I am unable to make reproducible example of the problem and post issue here just in hope you're give me any clue how to debug this problem. I have private part of site where over iframe inserted application with PIXI.sound. I have limited access to this part of the site. It was found that on tablets, with latest version of Chrome sound in this application not working. I've tested this with my own hands, I'd log in and heard sound, then I updated Chrome, again logged in, and heard no sound at all (not even when I click and it supposed to play, see this https://github.com/photonstorm/phaser/issues/2913). And there is no errors in console, I debug remotely and see that PIXI.sound.play is working, but hear no sound. I've failed to do reproducible example, because when I placed application in iframe alone I've heard sound. So may be you give me any hint how to debug this issue, I'll really appreciate it. Thanks in advance!

**Comment by bigtimebuddy** [comment]
Thanks for mentioning this @PainKKKiller. 

Based on the solution on Phaser, could you try adding the following [here](https://github.com/pixijs/pixi-sound/blob/master/src/webaudio/WebAudioContext.ts#L171) and see if that makes a difference?

```js
if (source.context.state === 'suspended') {
	source.context.resume();
}
```

**Comment by PainKKKiller** [comment]
Thanks for pointing this out I'll try tomorrow, and write here about results.

**Comment by PainKKKiller** [comment]
Sorry for long silence I was busy, but with your suggestion I overcame this bug. But anyway sound in android Chrome works only after tap on the screen. I couldn't get quickly into structure of your project, when I run 
` npm build` I get dist folder, where everything compiled, but code of AudioContext never taken from there, it used from libs folder, and I didn't bothered to research how to compile it. 
Anyway I solved problem in my SoundManager with this code:

`SoundManager.prototype.resumeSound = function() {
  if(PIXI.sound._context._ctx.state === "suspended") {
    PIXI.sound._context._ctx.resume().then(function() {
      	console.log("SoundManager#resuming Audio context");
    });
  }
}`

Hope this will help anyone who'll meet this problem.

**Comment by bigtimebuddy** [comment]
Thanks for this. Will work to get these fixed in. Could you tell me what version of Android Chrome so I can try to reproduce?

**Comment by PainKKKiller** [comment]
The link says it's reproducible from 55 version of Chrome, my version of Chrome is 62.0.3202.84. But again I say, it's strange, but I had working sound in single iframe with this version of Chrome
