### ISSUE TITLE
How to use it with webpack

### ISSUE THREAD

**Issue by bichotll** [pixijs/pixi-sound#50]
Hi, it may be just me, but I've been having trouble when I'm integrating this library with PIXI...

I concluded that one way was...
```js
import * as PIXILib from 'pixi.js';
import * as PIXISoundLib from 'pixi-sound';

PIXI = {...PIXILib, ...PIXISoundLib}
```
...which does not seem really nice tbh 😅

**Comment by bigtimebuddy** [comment]
Try:

import “pixi.js”;
import “pixi-sound”;

Then you have access to global PIXI object that way.

**Comment by bichotll** [comment]
How I didn't think about it that way?...
Working like a charm! Thanks! 👍
