### ISSUE TITLE
Add AMD support

### ISSUE THREAD

**Issue by koutoftimer** [pixijs/pixi-sound#53]
It is more requirement rather than a feature request.

Lets take a look at [pixi-plugin-example][1]. As you can see, at [this lines][2] plugin have to be attached to global `PIXI` variable as well as to be exported as a standalone module with its dependencies. At some point, this repo\plugin brokes one of the main approaches of how `pixi.js` is functioning.

Currently, there are a lot of module loaders that are built on top of AMD. I'm one of that users. Solution for me could be:
- Remove module loading (definition, dependency management, etc.) from the whole project - totally not what I'll do.
- Replace `pixi-sound` with some other sound library that is not part of `pixi-*` package.
- Add AMD support to this plugin ASAP.

   [1]: https://github.com/pixijs/pixi-plugin-example
   [2]: https://github.com/pixijs/pixi-plugin-example/blob/master/src/index.js#L7-L9

**Comment by koutoftimer** [comment]
Sorry, my fault, bad `requirejs` config.

**Comment by koutoftimer** [comment]
In order to use `pixi-sound` with requirejs you have to specify its dependencies manually with [shim][1] like this

```js
requirejs.config({
	paths: {
		'pixi': '../node_modules/pixi.js/dist/pixi.min',
		'pixi-sound': '../node_modules/pixi-sound/dist/pixi-sound'
	},
	shim: {
		'pixi-sound': {
			deps: ['pixi']
		}
	}
})
```

   [1]: http://requirejs.org/docs/api.html#config-shim

**Comment by koutoftimer** [comment]
@bigtimebuddy Perhaps, this can be added to wiki or readme in order to prevent similar issues from creating.

**Comment by bigtimebuddy** [comment]
Will do! Thanks for investigating.

**Comment by bigtimebuddy** [comment]
Added https://github.com/pixijs/pixi-sound/wiki#amd-integration
