### ISSUE TITLE
resource does not have a "sound" property

### ISSUE THREAD

**Issue by lebesnec** [pixijs/pixi-sound#55]
I have try to preload a .mp3 file using PIXI loader with this example: http://pixijs.io/pixi-sound/examples/#section-preloading

The ressource is loaded just fine but there is no "sound" property on it. If I use "data" instead it works:

`resources.bird.sound.play();` => does not work
`resources.bird.data.play();` => does work

**Comment by bigtimebuddy** [comment]
What version of pixi-sound are you using?

**Comment by lebesnec** [comment]
2.0.1

**Comment by bigtimebuddy** [comment]
Could you make a jsfiddle that reproduces this issue?

**Comment by lebesnec** [comment]
I did not manage to get jsfiddle to load a file, but here is the code: https://jsfiddle.net/vtyp3yyt/7/

if you manage to get past the loading error you should be able to reproduce the issue.

**Comment by ironchestgames** [comment]
I'm seeing the same thing with version 2.0.2, and when I try PIXI.sound in the console it's undefined.

I'm building with babel-preset-es2015 btw.

**Comment by ironchestgames** [comment]
I solved it, for my own at least.

I had forgotten to require('pixi-sound'), after that everything worked smoothly.

**Comment by lebesnec** [comment]
yes that fixed the problem. I use the 'import' syntax:

`import * as pixiSound from 'pixi-sound';`

**Comment by darklightblue** [comment]
Hi, I'm quite confused with the answer - so what you did is like:

```
    import * as PIXI from "pixi.js";
    import * as PIXI_SOUND from "pixi-sound";


... logic

      PIXI.Loader.shared.load(function(loader, resources) {
        if (resources.bird) {
          resources.bird.sound.play();
        }
      });
```

coz this still won't work for me

**Comment by lebesnec** [comment]
yes, but that was for pixi 4. I fyou are using the latest version it's probably different.

**Comment by darklightblue** [comment]
Any ideas on how it is currently handled?

**Comment by bigtimebuddy** [comment]
I created an example with Webpack +PixiJS v5 + pixi-sound:
https://github.com/bigtimebuddy/pixi-sound-webpack-example

Keep in mind, if you're using chrome, the first thing you play needs to be initiated on a user-interaction event, such as a mouse click.  Playing something after it's been loaded, will not necessarily start playing in some browsers.

**Comment by darklightblue** [comment]
Hmmm so I tried what you did but:
```
    import * as PIXI from "pixi.js";
    import * as PIXI_SOUND from "pixi-sound";
   import birdMusic from 'assets/bird-music.wav'

   const EFFECT_SOUNDS = { bird: birdMusic };

... logic

      // preloading the sounds
      for (let name in EFFECT_SOUNDS) {
         try {
           PIXI.Loader.shared.add(name, EFFECT_SOUNDS[name]);
        } catch (error) {}
      }

.. logic

      PIXI.Loader.shared.load(function(loader, resources) {
        if (resources.bird) {
            console.log(PIXI_SOUND.find('bird'))  //- this will become undefined

            PIXI_SOUND.play('bird); // this will throw an error

           // this will work but only for play and not other pixi-sound functions
           resources[sound].data.play(); 
        }
      });
```

It seems that when I add it on the "Pixi js" Loader it doesn't get added on the pixi-sound resources?

**Comment by c-andrews** [comment]
Did you ever get pixi-sound working? I'm using Pixi v5.1.3 and Pixi-Sound v3.0.3 but I cannot seem to get it to import. 

import * as PIXI from 'pixi.js';
import * from 'pixi-sound';

**PIXI.sound is undefined.**
Any help would be appreciated.

**Comment by bigtimebuddy** [comment]
@c-andrews 

That's the incorrect way to import:
```js
import * as PIXI from 'pixi.js';
import * as sound from 'pixi-sound';
```

`PIXI.sound` is only available if you are including via `<script>` elements. If you are bundling, there's no global `PIXI` object available.

**Comment by c-andrews** [comment]
So the import seems to be working both ways, however if I don't have 'sound' in my PIXI.application  constructor then it breaks it all. 

`constructor() {
    super({
      resolution: devicePixelRatio,
      ...screenSize,
    });
    ...
    sound;
    ...
  }`

Is there a way to get around it so I can just import 'sound' in my AudioManager?

**Comment by bigtimebuddy** [comment]
@c-andrews please file a new issue and include an example and/or more details about your environment. That description is not enough info to help you.

**Comment by c-andrews** [comment]
Thanks @bigtimebuddy, I'll try to sort it out for you

**Comment by tommy-tommy** [comment]
Nice to meet you. I am Japanese. 
I'm sorry if my English is wrong because I use translation.

Does not work unless `sound.init()` is called first!
This works fine if you call it!
`resources.bird.sound.play();` => does work :D

**Comment by honfai99** [comment]
@tommy-tommy 
Thank you! It works!
