### ISSUE TITLE
Loop doesn't work on sound sprite

### ISSUE THREAD

**Issue by barvynkoa** [pixijs/pixi-sound#57]
Seems like loop doesn't work correctly in this situation

```javascript
this.sound = Sound.from({
	url: this.audioPath,
	sprites: this.sprites
});
```

```javascript
this.sound.play({
	sprite: soundName,
	loop: true
});
```

Sound just play once...

examples
looping https://jsfiddle.net/8f5pvrq2/4/
not looping, why?  https://jsfiddle.net/uxzrq04b/12/

Is it a bug? does anybody know how it should work?

**Comment by flahhi** [comment]
Aha, it is because of this
https://andrii.tinytake.com/sf/MjQ1MzE3OV83NDA5MjE5

Looping not support when specifying an "end" time

sadly

**Comment by bigtimebuddy** [comment]
I think I originally didn't implement looping on sprites because I had assumed there would be obvious seaming issues on the fallback HTML5 <audio> element. I'm willing to change this and maybe add a warning about it in the documentation.

**Comment by rhausmair** [comment]
any chance to get that implemented in the next release?

**Comment by bigtimebuddy** [comment]
Added with #81
