### ISSUE TITLE
[feature] Support HTML5 Fallback

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-sound#6]
Need basic support for HTML5 fallback to support IE. Will probably add a new class (e.g. `LegacySound`) which wraps the HTML5 `<audio>` element but provides a common interface (e.g. `ISound`) for the existing Sound class which allows for basic support like play, pause, mute, volume and sprites. Loader middleware installing would need to check to see if WebAudio is support or else don't do anything so the Loader will return `<audio>` elements instead.

**Comment by hendrysadrak** [comment]
Waiting for this!

**Comment by bigtimebuddy** [comment]
Yeah, I've been resisting doing fallback support because programming `<audio>` API is a squirrelly mess of edge-cases. If I can just limit it to IE9 - 11, might make it easier. I also want to quarantine the compatibility code so that it's easy to jettison later. I haven't resolved an easy way to do that yet.

**Comment by dakom** [comment]
I know "me too" type comments are generally bad form - but just wanted to say this is awesome! Starting a new project and getting into PIXI, and my last time around the block was a little annoying having to manage loaders between Howler and PIXI... being able to keep all the core media handling in one place is really cool.... though without IE it's kindof a non-starter. Still I'm going to go this route and hope you magically solve the IE compatibility before release ;)

**Comment by bigtimebuddy** [comment]
I've been making some solid progress for IE and have something that's mostly functional on the **dev** branch. Hoping to tighten it up soon.

**Comment by bigtimebuddy** [comment]
HTML5 supported in **master**, will make a release soon
