### ISSUE TITLE
Google Chrome Crashes When Loading Audio

### ISSUE THREAD

**Issue by jmscreation** [pixijs/pixi-sound#63]
I have an issue where Google Chrome crashes when loading audio with Pixi Sound.
(Firefox loads up fine 99% of the time)
![scrnshot](https://user-images.githubusercontent.com/36322006/38750274-75b28462-3f22-11e8-8c67-a2329a0da76d.png)
I've tried everything I can but still can't seem to get it to be stable. It will load up correctly once in a while depending on how I save the audio file, e.g. really low quality with absolutely the lowest bitrate will sometimes work.

The mp3 file is 30 minutes long.
I am loading several other shorter mp3s as well.

Any ideas?
Help would greatly be appreciated.

**Comment by bigtimebuddy** [comment]
30 minute audio is not really the intended purpose of pixi-sound. It's mostly design for things that you want to preload completely. It's not feasible to decode that entire buffer at once. I would suggest that you use an `<audio>` element directly or use something else which does streaming/seeking without decoding the whole audio file.
