### ISSUE TITLE
Cannot set property 'loop' of null

### ISSUE THREAD

**Issue by Corginyan** [pixijs/pixi-sound#66]
`Uncaught TypeError: Cannot set property 'loop' of null`

Error in `instance.refresh()` function when change parameters like `volume` or `loop` on **paused** instances, because `this._source` is currently `null`.

Workaround - do not trigger setters, direct change` instance._loop`, `instance._volume` etc.

Not a real problem, i just writing a function to help me manipulate multiple instances of sound at the same time and get this in process. Sorry for my bad english.

**Comment by gfcrba** [comment]
It's a real big problem i think. Tried to use this lib in real project. I wrote externs (for haxe) and in project setting volume leads to uncaught exception.

**Comment by bigtimebuddy** [comment]
Thanks for letting me know. Will fix!

**Comment by gfcrba** [comment]
Didn't have time to investigate properly, but it seems that _source in refresh method is null. But why it is null i don't know. I clearly see that value to it assigns during play() call. If i can help some how fill free to ask.
