### ISSUE TITLE
console.assert

### ISSUE THREAD

**Issue by AlexSorochinsky** [pixijs/pixi-sound#67]
pixi-sound use console.assert function which not exist in MRAID sdk environments (mobile advertisement). At least MoPub SDK. I propose to replace this function on something simpler like console.log to have more compatibility with mobile MRAID advertisement.

**Comment by bigtimebuddy** [comment]
Sounds good. PR welcome

**Comment by bigtimebuddy** [comment]
In the meantime, you could add a polyfill for assert: https://github.com/gskinner/console-polyfill

**Comment by bigtimebuddy** [comment]
Fixed with #82, the release build will now drop all console statements.
