### ISSUE TITLE
Loading videos as audio files

### ISSUE THREAD

**Issue by StefanStojanovic** [pixijs/pixi-sound#69]
Hello,

I've started working on a kind of a wrapper around PIXI.js recently. My idea is to add some mechanisms I like using and to make the entire framework fit to my needs better. I've finished adding the core pixi module and I wanted pixi-sound.js to be the first extension I add to it. Let me describe you the problem I encountered.

So basically I need my wrapper to be an all round solution. For that purpose I need to be able to play videos as well as sounds. the problem I get is that when I add pixi-sound.js it changes <code><b>PIXI.loaders.Resource._xhrTypeMap/PIXI.loaders.Resource._loadTypeMap</b></code>, so mp4 video files are trying to be loaded and decoded as audio files because mp4 is in <code><b>PIXI.sound.utils.extensions</b></code>.

The first thing that popped in my mind was <code><b>PIXI.sound.useLegacy = true;</b></code> before adding resources and loading them, but even then I was still getting videos which had audio as data property of resource. After looking at https://github.com/pixijs/pixi-sound/blob/master/src/loader/LoaderMiddleware.ts I noticed that in non-legacy mode mp4 files were still loaded as audio files just in legacy mode. (Kind of obvious but you gotta try to see it fail...)

In the end I patched it for my purpose (as I always want to use mp4 files as videos) with the following code to revert it to default pixi setup
<code><b>PIXI.sound.utils.extensions.splice(PIXI.sound.utils.extensions.indexOf('mp4'), 1);
        PIXI.loaders.Resource.setExtensionXhrType('mp4', undefined);
        PIXI.loaders.Resource.setExtensionLoadType('mp4', PIXI.loaders.Resource.LOAD_TYPE.VIDEO);</b></code>

I guess this is maybe not an issue, but I wanted to report it just in case someone else comes across it. Also, if there is some explanation or reason why pixi-sound looks at mp4 files as just audio files, I'd like you to tell me so I understand it and see if my "revert" solution maybe has some problems I am not aware of at this moment.

Thanks in advance

**Comment by kreezii** [comment]
Thank you! I was getting crazy trying to load and play a video, I didn't know what was going wrong until I realised I was using pixi-sound library and that was the problem. As far as I could test it, your fix works without problems.

**Comment by StefanStojanovic** [comment]
Glad I could help! By the way, as this solution is a bit hackish, I rewrote it in typescript friendly manner. As far as I can tell from my tests it seems to work without any problems. Btw I know that extensions array and check is a bit of an overkill, but better safe then sorry :)

```typescript
const VIDEO_EXTENSIONS: string[] = ['mp4'];
window.addEventListener('load', () => {
    for (const extension of VIDEO_EXTENSIONS) {
        const extensionIndex: number = PIXI.sound.utils.extensions.indexOf(extension);
        if (extensionIndex !== -1) {
            PIXI.sound.utils.extensions.splice(extensionIndex, 1);
            PIXI.loaders.Resource.setExtensionLoadType(extension, PIXI.loaders.Resource.LOAD_TYPE.VIDEO);
            PIXI.loaders.Resource.setExtensionXhrType(extension, PIXI.loaders.Resource.XHR_RESPONSE_TYPE.DEFAULT);
        }
    }
});
```

**Comment by bigtimebuddy** [comment]
I will remove mp4 as an extension in the next version.
