### ISSUE TITLE
Spotify music will pause when safari is focus

### ISSUE THREAD

**Issue by majaray** [pixijs/pixi-sound#77]
I using pixi-sound for all my game projects, and I found out this issue recently which I got no clue at all.
When I running the game on my iOS safari browser, it will pause the Spotify music on background.
I try the other HTML5 games on the same device, but their game's music and Spotify music can be played at the same time without pausing either 1.

Anyone clue how should I overcome this issue?
I want my games able to keep playing the background music while other music apps playing as well.

**Comment by bigtimebuddy** [comment]
Unfortunately, that's a limitation of iOS and audio from the browser. You cannot have a WebAudio context running mixed with music in a background app (like Spotify). One app owns the audio focus or else it would be super confusing if you it stop on your headphones, it's unclear which audio stream you'd stop.  There's no way to work around this unless you build a native app. Sorry.

**Comment by majaray** [comment]
@bigtimebuddy it's okay. I just want to figure out the reason. Thank you!
But I'm still wonder, because I tried youtube web version + Spotify and it behaviour as the same, it will stop Spotify music when the video resume.
But how come some other HTML5 games are able to do that.
