### ISSUE TITLE
pixi sprites from pixi loader?

### ISSUE THREAD

**Issue by geddski** [pixijs/pixi-sound#86]
The sprites docs show how to use pixi-sound's sprite capabilities. But it's not clear how to use sprites when you're using a Pixi loader to load the mp3 file. Is this possible?

**Comment by bigtimebuddy** [comment]
If you want to externalize the sprite data you should load that as JSON and assign to the loaded Sound by using addSprites method on the Sound object. You may want to make your own Loader middleware for this if you need the convenience.

**Comment by geddski** [comment]
@bigtimebuddy I'm having a hard time figuring out how to do it. I have the JSON object defined:

```js
const sprites = {
  SFX_arm_transform: { start: 0.0, end: 1.033 },
  SFX_arm_transformBack: { start: 1.333, end: 2.567 },
  SFX_grapple_chain_loop: { start: 2.867, end: 4.061 },
  SFX_grapple_close: { start: 4.361, end: 4.995 }
   ...
}
```

And I can load the combined mp3 with the PIXI loader:

```js
loader.add("combined", "/path/to/combined.mp3")
```

This creates a single sound clip named `combined` that can be played, but I'm unsure how to create many sounds from this sprite.

**Comment by bigtimebuddy** [comment]
I was thinking something like this:

```js
const loader = new PIXI.loaders.Loader();
loader.add('sprites', 'sprites.json');
loader.add('combined', 'combined.mp3');
loader.load((loader, resources) => {
  resources.combined.sound.addSprites(resources.sprites.data);
});

**Comment by geddski** [comment]
Ahh got it. Thanks for the help @bigtimebuddy.
