### ISSUE TITLE
can't stop a looping sprite?

### ISSUE THREAD

**Issue by geddski** [pixijs/pixi-sound#87]
I have sound sprites for a game character. He has a grappling hook sound (sprite) that plays while he's moving through the air. When he reaches his destination I want to stop the sound. Sprites don't appear to have a `stop()` method though like regular sounds do. I tried stopping the parent sound but that interferes with the character's other sounds that are playing at the same time.

Is there a way to stop a looping sprite?

Or maybe even better would be a way to slice out the single sprite mp3 file into regular Sound instances?

**Comment by bigtimebuddy** [comment]
When you do `Sound.play` it return the SoundInstance. You can then stop this later if you save a reference to it.

**Comment by geddski** [comment]
aha! Thank you!

**Comment by geddski** [comment]
@bigtimebuddy is there by chance a way to set the volume for a sprite, without setting the volume for an entire parent sound?

**Comment by bigtimebuddy** [comment]
Yeah same thing...
```js
const instance = Sound.play('mySprite');
instance.volume = 0.5;
```
Keep in mind, after you stop or end the sprite, you should not keep the instance reference since the Sound instances are recycled.

**Comment by geddski** [comment]
won't that start playing before the volume change is in effect? Or does `play()` not happen till the next requestanimationframe or something?

**Comment by bigtimebuddy** [comment]
That shouldn’t be an issue. Setting it that way happens immediately.
