### ISSUE TITLE
[TUTO] Manage and create spriteAudio data with Audacity

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-sound#91]
Just a little fast tips for who like me search and want manage spriteAudio with a sofware.
If like me your audio source files are from pro like `https://www.boomlibrary.com/`
All file are mixed with multi sound.

1: download **audacity** it free and openSource

2:Open you audio file in `audacity`, in this case is "BT_BOING_Rubber_Band_Swing.wav"

3:Select and hilight lite a region you want
![image](https://user-images.githubusercontent.com/24865815/56443383-6342a400-62c2-11e9-801c-053b1ef30f0b.png)

4: use key `ctrl+B` to add label regions, and name it.
![image](https://user-images.githubusercontent.com/24865815/56443407-879e8080-62c2-11e9-9212-1e02f14f749e.png)

5:do it for all (select,ctrl+B,name)
You can also ajuste live the region with `shift+click`
![image](https://user-images.githubusercontent.com/24865815/56443467-caf8ef00-62c2-11e9-97e1-6cbbede368bf.png)

6: Export label in text data 
Be sure you name it with similar name for make easy manage in window.
in this case `BT_BOING_Rubber_Band_Swing_data.txt`
![image](https://user-images.githubusercontent.com/24865815/56443498-f24fbc00-62c2-11e9-9932-d17b8ddc2548.png)

7:load audio and audio data in pixi.Loader.

8: convert the txt in a valid json for pixi-sound.
with this method
```javascript
        /**Data are a example of the result from loader texty*/
        const data = `0.225725	0.767466	boing_1
        2.257252	2.988601	boing_2
        4.577707	5.354201	boing_3
        6.871075	7.620482	boing_4
        9.056094	9.706183	boing_5
        11.322375	11.864116	boing_5
        `;
        const data_json = {};
        const lines = data.split("\n");
        lines.forEach(line => {
            if(line){
                line = line.split("\t");
                data_json[line[2]] = { start: line[0], end: line[1] };
            };
        });
        console.log('data_json: ', data_json);
```

9:Enjoy spriteAudio in Pixi-sound
![image](https://user-images.githubusercontent.com/24865815/56444057-275d0e00-62c5-11e9-940a-08c0b64006f9.png)

**Comment by bigtimebuddy** [comment]
I moved this to: https://github.com/pixijs/pixi-sound/wiki/Generating-AudioSprites-with-Audacity

Thanks for doing this @djmisterjon.

**Comment by djmisterjon** [comment]
ok, sorry and thank for fix my bad English :)
