### ISSUE TITLE
pauseAll() not working in legacy/HTML5 Audio mode

### ISSUE THREAD

**Issue by ericente** [pixijs/pixi-sound#93]
Individual sounds are able to be paused by calling `pause()` on them directly in legacy mode, but pauseAll() does not work.

**Comment by bigtimebuddy** [comment]
Could you see if `togglePauseAll()` works? I think these are implemented slightly different. Would be good to know if that works in legacy.

**Comment by ericente** [comment]
Yep, `togglePauseAll()` does work
