### ISSUE TITLE
Question about code

### ISSUE THREAD

**Issue by Corginyan** [pixijs/pixi-sound#95]
Seems like that line never going to be executed
https://github.com/pixijs/pixi-sound/blob/36fe339b32c911656dced3755e9712aa24ebf2c5/src/webaudio/WebAudioInstance.ts#L449
Because `this._source` already `null` by previously called `this._internalStop();`
https://github.com/pixijs/pixi-sound/blob/36fe339b32c911656dced3755e9712aa24ebf2c5/src/webaudio/WebAudioInstance.ts#L446
Right here
https://github.com/pixijs/pixi-sound/blob/36fe339b32c911656dced3755e9712aa24ebf2c5/src/webaudio/WebAudioInstance.ts#L562

**Comment by bigtimebuddy** [comment]
You’re right, good find. I think we need disconnect in internalStop and remove the bit in destroy. Will probably solve that memory leak too. Want to put together a PR?

**Comment by Corginyan** [comment]
No, thanks.

**Comment by bigtimebuddy** [comment]
Fixed in 3.0.0
